### ISSUE TITLE
Notebook extension is stripped off in jobs spec

### ISSUE THREAD

**Issue by iandexter** [databricks/run-notebook#30]
Consider the following `action.yml`:
```
- name: Run notebook
  uses: databricks/run-notebook@main
  with:
    local-notebook-path: notebooks/test.py
    ...
    git-provider: 'gitHubEnterprise'
    git-commit: ${{ github.sha }}
    ...
```

The jobs spec in Databricks is:
```
{
  name: "run tests"
  tasks {
    task_key: "notebook-task"
    task {
      notebook_task {
        notebook_path: "notebooks/test"
      }
    }
    cluster_spec {
      existing_cluster_id: "REDACTED"
    }
  }
  git_source {
    git_url: "REDACTED"
    git_provider: "gitHubEnterprise"
    git_commit: "REDACTED"
  }
}
```

This results in a job run failure:
```Notebook not found: notebooks/test```

It may be because the extension is [stripped](https://github.com/databricks/run-notebook/blob/main/dist/main/index.js#L320-L323) from the `local-notebook-path`?
