### ISSUE TITLE
[question] how to give access to an user without a group

### ISSUE THREAD

**Issue by codebydant** [databricks/run-notebook#43]
Hi there,

I was wondering if the following section could uses "user_name" instead "group_name"

```yml
# Grant all users view permission on the notebook results, so that they can
          # see the result of our CI notebook 
          access-control-list-json: >
            [
              {
                "group_name": ",
                "permission_level": "CAN_MANAGE"
              }
            ]
```
